dunesim/EventGenerator/CORSIKAprotodunedp/CORSIKAGendp_module.cc, dunesim/EventGenerator/CORSIKAprotodunedp/Gen311_module.cc, dunesim/SimFilter/LArG4ExtCounterFilter_module.cc
Pursuant to LArSoft/larcorealg#33
=> Accommodate breaking changes in geometry

dunesim/EventGenerator/CORSIKAprotodunedp/CORSIKAGendp_module.cc, dunesim/EventGenerator/CORSIKAprotodunedp/Gen311_module.cc, dunesim/SimFilter/LArG4ExtCounterFilter_module.cc
=> Revert "Accommodate breaking changes in geometry"

dunesim/LArG4/IonAndScint_dune.fcl, dunesim/Simulation/larg4services_dune.fcl
Created scintillation and ionisation instances for the hybrid model, with ProtoDUNE-HD v3 geometry.
=> Hybrid model for ProtoDUNE-HD

dunesim/EventGenerator/CORSIKAprotodunedp/CORSIKAGendp_module.cc, dunesim/EventGenerator/CORSIKAprotodunedp/Gen311_module.cc, dunesim/SimFilter/LArG4ExtCounterFilter_module.cc
Pursuant to LArSoft/larcorealg#33
=> Accommodate geometry interface changes (redo)

dunesim/Simulation/simulationservices_dune.fcl
Make FD2-VD largeant parameters.
The functionality added by the PR is not used anywhere in any of the develop repos, so can be added immediately.
=> Make FD2-VD largeant parameters

dunesim/DetSim/SimWireDUNE10kt_module.cc, dunesim/DetSim/SimWireDUNE35t_module.cc, dunesim/EventGenerator/CORSIKAprotodunedp/CORSIKAGendp_module.cc, dunesim/EventGenerator/CORSIKAprotodunedp/Gen311_module.cc, dunesim/EventGenerator/NuE/NuEScatterGen_module.cc, dunesim/EventGenerator/ProtoDUNEBeam_module.cc, dunesim/EventGenerator/ProtoDUNETriggeredBeam_module.cc, dunesim/SimFilter/GenExtCounterFilter_module.cc, dunesim/SimFilter/LArG4ExtCounterFilter_module.cc
=> Changes for art 3.12

dunesim/Simulation/larg4services_dune.fcl
As requested by @lpaulucc in dunecore PR [#69,](https://github.com/DUNE/dunecore/pull/69) I modified larg4detector for dune-vd 1x8x6 30 deg.
=> Modify the larg4 service for dune-vd 1x8x6_3view_30deg.

dunesim/EventGenerator/Radiological/dune_radiological_model_decay0_v3_2.fcl
Configuration file for the new DUNE radiological background model.
(I would like to wait for the next dune release to test the cathode generation before merging, if that is ok)
=> Radiological model decay0 v3.2

dunesim/Simulation/larg4services_dune.fcl
ProtoDUNE-VD sim/reco chain pointing to `protodunevd_v3_refactored.gdml` GDML file
=> Update protodunevd driftX geometry to v3

dunesim/EventGenerator/prodsingle_iceberg_refactored.fcl
Added WireCell 2D simulation in the simulation chain.
Need latest update in the develop branch of **dunereco**.
Here is the raw waveform from the simulation:
=> add detsim

dunesim/Simulation/larg4services_dune.fcl
=> Update PDVD geometry to v4

dunesim/EventGenerator/GENIE/genie_dune.fcl
Adding an additional flux rotation that is appropriate to the VD geometry
=> Adding the correct rotation for VD atmospherics

dunesim/SimFilter/larg4particlefilter_dune.fcl
Add extra g4 particle filter configurations.
=> ADD GAMMA AND ELECTRON FILTER CONFIGS

dunesim/EventGenerator/Radiological/protodunehd_radiological_model_decay0.fcl
New PDHD generation FHICL for simulation of radiologicals in structural parts (CPA, APA, FC beams).
Takes default activities from FD1-HD model.
=> Add definitions for PDHD structural radiologicals

dunesim/EventGenerator/Radiological/protodunehd_radiological_model_decay0.fcl
Define PDHD 207Bi source volume and activity.
Comes with the following PRs:
- https://github.com/DUNE/dunesw/pull/157
- https://github.com/DUNE/dunecore/pull/130
=> Add PDHD 207Bi source simulation

dunesim/EventGenerator/marley_dune.fcl
Similarly to what is done in the same file for the flat spectrum, I added the ES interactions in the marley reactions for dune when using the nue spectrum.
I can't find a way to add @sjgardiner to reviewers.
=> Added ES interactions for nue_spectrum fcl config

dunesim/EventGenerator/GENIE/dk2nuconfigs/GDk2Nu.xml, dunesim/EventGenerator/GENIE/genie_dune.fcl, dunesim/Simulation/larg4services_dune.fcl
This adds
- a GENIE flux window for FD1-HD
- a refactored larg4 sensitive detector block for FD1-HD
=> LBL simulation changes for FD1-HD 10kt

dunesim/DetSim/Tool/test/test_IdealAdcSimulator.cxx, dunesim/DetSim/fcl/detsimtools_dune.fcl
=> Revert "Changed adc Nbit to 14, new DAQ standard"

dunesim/DetSim/Tool/test/test_IdealAdcSimulator.cxx, dunesim/DetSim/fcl/detsimtools_dune.fcl
=> Revert "Change adc range from 12 to 14 bits, new DAQ standard"

dunesim/GapChargeTransport/CMakeLists.txt
Fixed missing dependency as suggested by Wooyoung Jang
=> Update CMakeLists.txt in dunesim/GapChargeTransport
