dunesim/EventGenerator/GENIE/addgenie_dune.fcl
The .fcl file has incorrect coordinates for the active volume.  This is a mistake that was inherited from old code when it got pushed originally.  This update is to correct that mistake.
=> Correcting TPC Coordinates

dunesim/EventGenerator/GENIE/addgenie_dune.fcl
I forgot to push this when I added in all the nnbar, pdk, and atm. model types to dunesw for production.  This corrects the issue that production was having.
=> I added in the missing file lists for the atm, nnbar, and pdk samples.

dunesim/Simulation/larg4services_dune.fcl
The dedicated service block disables keeping the shower children.
Sibling PR: https://github.com/DUNE/dunecore/pull/4
=> Create dedicated particle list action service for the VD FD 

dunesim/DetSim/Module/SimWireClnSigDUNE_module.cc, dunesim/DetSim/Module/SimWireUniqNoiseDUNE_module.cc, dunesim/DetSim/Service/CMakeLists.txt, dunesim/DetSim/Service/SPhaseUniqChannelNoiseService.h, dunesim/DetSim/Service/SPhaseUniqChannelNoiseService_service.cc, dunesim/EventGenerator/NuE/NuEScatterGen.fcl, dunesim/EventGenerator/NuE/NuEScatterGen_module.cc
provided new versions of services for generating unique noise per channel.  Current version of channel noise service reuses noise waveforms form a pre-generated pool of waveforms.  This leads to correlations that may have undesirable effects for ML training.  The versions of modules and services provided in this PR addresses this issue.  There is also a updated version of NuEScatterGen in this PR that includes fixes from James (Jieran) Shen and some updates that allow specifying custom BRs per flavor and a simpler way to generate a flat energy spectrum.
=> Modules/servcies for unique noise per channel and updates/fixes for NuEScatterGen

dunesim/DetSim/Service/Dune35tSimChannelExtractService_service.cc, dunesim/DetSim/SimWireDUNE35t_module.cc, dunesim/DetectorVariations/RandomChannelStatusService_service.cc, dunesim/EventGenerator/CORSIKAprotodunedp/CORSIKAGendp_module.cc, dunesim/EventGenerator/CORSIKAprotodunedp/Gen311_module.cc, dunesim/SimFilter/GenExtCounterFilter_module.cc, dunesim/SpaceCharge/SpaceChargeProtoDUNEdp.cxx
Pursuant to LArSoft/larcorealg#34.
=> Accommodate breaking changes in geometry

dunesim/LArG4/IonAndScint_dune.fcl
With the computable graph method, there is no need to separate the TPC active volume from the external volume in the IonAndScint step.
=> Setup for ANN IonAndScint

dunesim/Simulation/simulationservices_dune.fcl
This is needed to get the correct LY for the region between the field cage and cryostat wall (where the membrane photon detectors are located) (From Laura below)
=> Enable UseModLarqlRecomb as requested by Laura

dunesim/Simulation/larg4services_dune.fcl, dunesim/Simulation/simulationservices_dune.fcl
This can be merged
- Use ProtoDUNE values for diffusion.
- Wirecell will not pick up these values by default; the wirecell fcl in dunereco will need to be updated to point to the diffusion values here.
- Dedicated dune FD particle list action
=> HD production changes (replaces PR: https://github.com/DUNE/dunesim/pull/33) 

dunesim/LArG4/IonAndScint_dune.fcl, dunesim/Simulation/larg4services_dune.fcl
Change the dunevd larg4 detector service parameters from volExternalActive, to volCryostat, in order to simulate energy deposits in the full liquid argon volume. This PR is related with a PR in dunecore: https://github.com/DUNE/dunecore/pull/61
=> Update dunevd larg4 detector service 

dunesim/Simulation/larg4services_dune.fcl
LArG4 detector for the 1x2x6 hardcodes the version number into the fcl param name and the value.  Remove the specified versions and let geometry_dune.fcl handle which version to point to.
Needs https://github.com/DUNE/dunecore/pull/79
=> Remove version for gdml and let geometry_dune.fcl handle that

dunesim/EventGenerator/Radiological/dune_radiological_model_decay0_vd_1x8x14.fcl
The cathode volume changed name from v4 to v5 VD geometry. This needed to be fixed in the radiological config file for the decay 0 model.
=> Fixing bkg cathode generator volume for VD v5 1x8x14 geo

dunesim/EventGenerator/GENIE/genie_dune.fcl
Following comments obtained on https://github.com/DUNE/dunesw/pull/77 , adding to `genie_dune.fcl` a new config for generating a weighted atmospheric sample.
=> Implementing config for HEP WG production

dunesim/Simulation/larg4services_dune.fcl
I added a larg4 block that was missing for protodune-vd driftY simulation workflow
=> add protodune-vd driftY larg4 service block

dunesim/EventGenerator/Radiological/dune_radiological_model_decay0_v3_4_for1x2x6.fcl, dunesim/EventGenerator/Radiological/prodbackground_radiological_decay0_v3_4_dune10kt_1x2x6.fcl
Revision v3_5 for new assays based 'Radiological Model v3' for HD 1x2x6, HD 1x2x2 and VD 1x8x6 (requiring corresponding producer files). 
[As APA electronics boards in geometry break Wire-Cell reco, added fix for those backgrounds, independent now of boards being present in geometry]
-Juergen Reichenbacher (SDSMT) 2023/12/11
=> Rev. v3_5 for 'Radiological Model v3' for HD 1x2x6 (fcl and producer) to address Wire-Cell reco issue

dunesim/EventGenerator/marley_dune.fcl
Including buffer region in the XY plane for generating marley events in VD (adding to the buffer region along the YZ plane: distance 65cm - 8cm to be consistent with what Pablo has been using in his studies)
=> VD buffer region along Z included for marley gen

dunesim/SimFilter/larg4particlefilter_dune.fcl
This PR configures a fcl parameter set for larevt's LArG4ParticleFilter.
This filter selects events in which there is a neutron with TPC activity.  
This configuration relies on geant4 creating a new neutron any time a neutron interacts with a medium, which should be the case.
The filter exploits this and selects any event in which a neutron appears to stop in the TPC.
=> A LArG4ParticleFilter fcl config for selecting neutrons with TPC activity

dunesim/EventGenerator/Radiological/dune_radiological_model_decay0_v3_5_for1x2x2.fcl, dunesim/EventGenerator/Radiological/prodbackground_radiological_decay0_v3_5_dune10kt_1x2x2.fcl
dune_radiological_model_decay0_v3_5_for1x2x2.fcl  with  prodbackground_radiological_decay0_v3_5_dune10kt_1x2x2.fcl (JR):  
As APA electronics boards in geometry break Wire-Cell reco, added fix for those backgrounds, independent now of boards being present in geometry (-> [...]_gammas_in_APAboards). 
HD 1x2x2 version is same as HD 1x2x6 version, except external backgrounds stop at z=490cm and face plane at z=490cm is left out to make it more representative for a 10 kton HD module. 
Moreover, z-positions of [...]_gammas_in_APAboards changed down from 1395. cm for HD 1x2x6 to 464. cm for HD 1x2x2 . 
Radon daughter plate-out decay chain on PDS starts now with Pb210 as in HD 1x2x6 v3_5.
=> APA electronics boards hack for Radiological Model v3_5 for HD 1x2x2

dunesim/EventGenerator/marley_dune.fcl, dunesim/Simulation/larg4services_dune.fcl
I added the default block `dune10kt_1x2x2_larg4detector`, that features the v6 of the geometry. 
The table `dune10kt_1x2x2_v4_larg4detector` should in my opinion be dropped, but I left it for the moment in case I'm wrong or in case somebody is still using it. I can remove it if you agree it is not needed anymore.
=> Using larg4det geometry v4 in 1x2x2

dunesim/DetSim/Tool/test/test_IdealAdcSimulator.cxx, dunesim/DetSim/fcl/detsimtools_dune.fcl
Since might people are still using 1D simulation, it would be better if they used the correct ADC range.
Linked to the update of Nbit in wirecell https://github.com/DUNE/dunereco/pull/132, but independent from it. To be decided if this MR can go in before that or if the change should happen in both places in the same dunesw version (maybe better?).
Small note: the pre-existent printout in the test Tool module is not great since values are hardcoded, but maybe it's not really used.
=> Changed adc Nbit to 14, new DAQ standard

dunesim/EventGenerator/marley_dune.fcl
I updated the marley_dune.fcl to accommodate a few changes:
- there are new spectrum files that shall be used in place of the old ones, under `/pnfs/dune/persistent/stash/Flux/Supernova/v2`
- the blocks for the different spectra have been created, used by the fcls in dunesw
- created es and cc configs, never actually using both at the same time
- I reorganized the layout of the file for improved clarity, dividing SN and solar
=> Update marley standard configurations

dunesim/EventGenerator/marley_dune.fcl
Since https://github.com/DUNE/dunesw/pull/174 is not in v10_06_00, the fix of the typo from gvkm to gkvm actually breaks some configurations. 
I just added back the blocks with the typo inheriting from the correct ones, so that no problems should rise.
=> PATCH: added back a marley block with a typo for backwards compatibility
